# These are non-BIDS fields that can be added by CuBIDS
derived_params:
  anat:
    Dim1Size:
      suggest_variant_rename: yes
    Dim2Size:
      suggest_variant_rename: yes
    Dim3Size:
      suggest_variant_rename: yes
      tolerance: 20
    NSliceTimes: {}
    NumVolumes:
      suggest_variant_rename: yes
    Obliquity:
      suggest_variant_rename: yes
    VoxelSizeDim1:
      tolerance: 0.1
      precision: 4
      suggest_variant_rename: yes
    VoxelSizeDim2:
      tolerance: 0.1
      precision: 4
      suggest_variant_rename: yes
    VoxelSizeDim3:
      tolerance: 0.1
      precision: 3
      suggest_variant_rename: yes
  dwi:
    Dim1Size:
      suggest_variant_rename: yes
    Dim2Size:
      suggest_variant_rename: yes
    Dim3Size:
      suggest_variant_rename: yes
      tolerance: 10
    NSliceTimes: {}
    NumVolumes:
      suggest_variant_rename: yes
    Obliquity:
      suggest_variant_rename: yes
    VoxelSizeDim1:
      tolerance: 0.2
      suggest_variant_rename: yes
    VoxelSizeDim2:
      tolerance: 0.2
      suggest_variant_rename: yes
    VoxelSizeDim3:
      tolerance: 0.2
      precision: 3
      suggest_variant_rename: yes
  fmap:
    Dim1Size:
      suggest_variant_rename: yes
    Dim2Size:
      suggest_variant_rename: yes
    Dim3Size:
      suggest_variant_rename: yes
    NSliceTimes: {}
    NumVolumes:
      suggest_variant_rename: yes
    Obliquity:
      suggest_variant_rename: yes
    VoxelSizeDim1:
      tolerance: 0.2
      suggest_variant_rename: yes
    VoxelSizeDim2:
      tolerance: 0.2
      suggest_variant_rename: yes
    VoxelSizeDim3:
      tolerance: 0.2
      suggest_variant_rename: yes
  func:
    Dim1Size:
      suggest_variant_rename: yes
    Dim2Size:
      suggest_variant_rename: yes
    Dim3Size:
      suggest_variant_rename: yes
      tolerance: 10
    NSliceTimes: {}
    NumVolumes:
      suggest_variant_rename: yes
    Obliquity:
      suggest_variant_rename: yes
    VoxelSizeDim1:
      tolerance: 0.2
      suggest_variant_rename: yes
    VoxelSizeDim2:
      tolerance: 0.2
      suggest_variant_rename: yes
    VoxelSizeDim3:
      tolerance: 0.2
      precision: 3
      suggest_variant_rename: yes
  perf:
    Dim1Size:
      suggest_variant_rename: yes
    Dim2Size:
      suggest_variant_rename: yes
    Dim3Size:
      suggest_variant_rename: yes
    NSliceTimes: {}
    NumVolumes:
      suggest_variant_rename: yes
    Obliquity:
      suggest_variant_rename: yes
    VoxelSizeDim1:
      tolerance: 0.2
      suggest_variant_rename: yes
    VoxelSizeDim2:
      tolerance: 0.2
      suggest_variant_rename: yes
    VoxelSizeDim3:
      tolerance: 0.2
      suggest_variant_rename: yes
  other:
    Dim1Size:
      suggest_variant_rename: yes
    Dim2Size:
      suggest_variant_rename: yes
    Dim3Size:
      suggest_variant_rename: yes
    NSliceTimes: {}
    NumVolumes:
      suggest_variant_rename: yes
    Obliquity:
      suggest_variant_rename: yes
    VoxelSizeDim1:
      tolerance: 0.2
      suggest_variant_rename: yes
    VoxelSizeDim2:
      tolerance: 0.2
      suggest_variant_rename: yes
    VoxelSizeDim3:
      tolerance: 0.2
      suggest_variant_rename: yes
# These fields reflect relationships between images.
# Not modality specific
relational_params:
  FieldmapKey:
    # can be
    # "bool": a single column with true if an IntendedFor is present
    # "columns": List all intended key groups in separate columns (IntendedForXX)
    display_mode: bool
    suggest_variant_rename: yes
  IntendedForKey:
    # can be
    # "bool": a single column with true if an IntendedFor is present
    # "columns": List all intended key groups in separate columns (IntendedForXX)
    display_mode: bool
# BIDS fields to directly include in the Parameter Groupings
sidecar_params:
  anat:
    EchoTime:
      tolerance: 0.001
    EffectiveEchoSpacing:
      tolerance: 0.00001
      precision: 4
    FlipAngle: {}
    MultibandAccelerationFactor: {}
    NumberOfVolumesDiscardedByScanner: {}
    NumberOfVolumesDiscardedByUser: {}
    ParallelAcquisitionTechnique: {}
    #ParallelReductionFactorInPlane: {}
    PartialFourier: {}
    #PhaseEncodingDirection: {}
    RepetitionTime:
      tolerance: 0.01
      precision: 3 
      suggest_variant_rename: yes
    SliceEncodingDirection: {}
    TotalReadoutTime:
      tolerance: 0.001
    VolumeTiming:
      tolerance: 0.000001
  dwi:
    EchoTime:
      tolerance: 0.1
      precision: 4
    EffectiveEchoSpacing:
      tolerance: 0.01
      precision: 4
      suggest_variant_rename: yes
    FlipAngle: {}
    MultibandAccelerationFactor: {}
    NumberOfVolumesDiscardedByScanner: {}
    NumberOfVolumesDiscardedByUser: {}
    ParallelAcquisitionTechnique: {}
    ParallelReductionFactorInPlane: {}
    PartialFourier: {}
    PhaseEncodingDirection:
      suggest_variant_rename: yes
    RepetitionTime:
      tolerance: 0.000001
      precision: 4
      suggest_variant_rename: yes
    SliceEncodingDirection: {}
    TotalReadoutTime:
      tolerance: 0.02
      suggest_variant_rename: yes
    VolumeTiming:
      tolerance: 0.000001
  fmap:
    EchoTime:
      tolerance: 0.001
    EffectiveEchoSpacing:
      tolerance: 0.00001
    FlipAngle: {}
    MultibandAccelerationFactor: {}
    NumberOfVolumesDiscardedByScanner: {}
    NumberOfVolumesDiscardedByUser: {}
    ParallelAcquisitionTechnique: {}
    ParallelReductionFactorInPlane: {}
    PartialFourier: {}
    PhaseEncodingDirection:
      suggest_variant_rename: yes
    RepetitionTime:
      tolerance: 0.000001
      precision: 4
      suggest_variant_rename: yes
    SliceEncodingDirection: {}
    TotalReadoutTime:
      tolerance: 0.001
    VolumeTiming:
      tolerance: 0.000001
  func:
    EchoTime:
      tolerance: 0.002
    EffectiveEchoSpacing:
      tolerance: 0.0002
      suggest_variant_rename: yes
    FlipAngle: {}
    MultibandAccelerationFactor: {}
    NumberOfVolumesDiscardedByScanner: {}
    NumberOfVolumesDiscardedByUser: {}
    ParallelAcquisitionTechnique: {}
    ParallelReductionFactorInPlane: {}
    PartialFourier: {}
    PhaseEncodingDirection:
      suggest_variant_rename: yes
    RepetitionTime:
      tolerance: 0.001
      precision: 4
      suggest_variant_rename: yes
    SliceEncodingDirection: {}
    TotalReadoutTime:
      tolerance: 0.01
      suggest_variant_rename: yes
    VolumeTiming:
      tolerance: 0.000001
  perf:
    EchoTime:
      tolerance: 0.000001
    EffectiveEchoSpacing:
      tolerance: 0.00001
    FlipAngle: {}
    MultibandAccelerationFactor: {}
    NumberOfVolumesDiscardedByScanner: {}
    NumberOfVolumesDiscardedByUser: {}
    ParallelAcquisitionTechnique: {}
    ParallelReductionFactorInPlane: {}
    PartialFourier: {}
    PhaseEncodingDirection:
      suggest_variant_rename: yes
    RepetitionTime:
      tolerance: 0.000001
      precision: 4
      suggest_variant_rename: yes
    SliceEncodingDirection: {}
    TotalReadoutTime:
      tolerance: 0.01
    VolumeTiming:
      tolerance: 0.000001
  other:
    EchoTime:
      tolerance: 0.001
    EffectiveEchoSpacing:
      tolerance: 0.00001
    FlipAngle: {}
    MultibandAccelerationFactor: {}
    NumberOfVolumesDiscardedByScanner: {}
    NumberOfVolumesDiscardedByUser: {}
    ParallelAcquisitionTechnique: {}
    ParallelReductionFactorInPlane: {}
    PartialFourier: {}
    PhaseEncodingDirection:
      suggest_variant_rename: yes
    RepetitionTime:
      tolerance: 0.000001
      suggest_variant_rename: yes
    SliceEncodingDirection: {}
    TotalReadoutTime:
      tolerance: 0.001
    VolumeTiming:
      tolerance: 0.000001
